### ISSUE TITLE
Code style

### ISSUE THREAD

**Issue by OlgaYubil** [nea2310/Metalamp-2nd-task#2]
Код будет лучше читаться, если отделить объявление миксина от импортов пустой строкой
<img width="539" alt="Снимок экрана 2022-04-21 в 11 26 29" src="https://user-images.githubusercontent.com/82147736/164454464-fc79f19c-e2ae-4222-a2a3-5dfc3c0c84c8.png">

**Comment by OlgaYubil** [comment]
Нет смысла выносить в переменную elemName='toggle', это только ухудшает читаемость кода. Если же где-то еще понадобится в наименовании класса подставлять значение динамически, то лучше использовать шаблонные строки вместо конкатенации.
И второй момент - нужно везде, где только можно в коде использовать деструктуризацию параметров, например так: 
```
toggle({ name = '', labelText = '', } ={})
```

<img width="646" alt="Снимок экрана 2022-04-21 в 11 23 22" src="https://user-images.githubusercontent.com/82147736/164455079-6b34501f-e039-471f-9e00-18139b18bacb.png">

**Comment by nea2310** [comment]
Выносила имя корневого селектора в переменную, руководствуясь такими соображениями: если возникнет необходимость использовать компонент в другом проекте, где корневой селектор потребуется назвать по-другому, то в в pug-файле нужно будет переименовать только в одном месте. 

Возможно ли оставить вынесение имени в переменную, а для лучшей читаемости заменить везде в теле pug-файлов конкатенацию на шаблонные строки? 

![image](https://user-images.githubusercontent.com/61518711/164968986-90f2204d-add1-49fb-9d8b-78e9f13be11f.png)
